export const apikey =
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xenFpdnVreXZ1c3lxeWRqa2htIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxMDc1MTY2NSwiZXhwIjoyMDI2MzI3NjY1fQ.hCyXZaN72COaAi-OKG4rxjK6NuPsVN61O166Dboe6GQ";
export const endpoint =
  "https://nqzqivukyvusyqydjkhm.supabase.co/rest/v1/recipes";
